apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

dependencies {
    implementation project(':game-session-service:domain')
    implementation project(':game-session-service:infrastructure:persistence')
    implementation project(':game-session-service:infrastructure:game-engine-integration')
    implementation project(':game-session-service:infrastructure:rest')
    implementation project(':game-session-service:infrastructure:websocket')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
